# Copyright 2021 The Tekton Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# coding: utf-8

"""
    Tekton

    Tekton Pipeline  # noqa: E501

    The version of the OpenAPI document: v0.49.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import tekton_pipeline
from tekton_pipeline.models.v1_pipeline_task_run_template import V1PipelineTaskRunTemplate  # noqa: E501
from tekton_pipeline.rest import ApiException

class TestV1PipelineTaskRunTemplate(unittest.TestCase):
    """V1PipelineTaskRunTemplate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V1PipelineTaskRunTemplate
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = tekton_pipeline.models.v1_pipeline_task_run_template.V1PipelineTaskRunTemplate()  # noqa: E501
        if include_optional :
            return V1PipelineTaskRunTemplate(
                pod_template = tekton_pipeline.models.pod/template.pod.Template(
                    affinity = None, 
                    automount_service_account_token = True, 
                    dns_config = None, 
                    dns_policy = '0', 
                    enable_service_links = True, 
                    env = [
                        None
                        ], 
                    host_aliases = [
                        None
                        ], 
                    host_network = True, 
                    image_pull_secrets = [
                        None
                        ], 
                    node_selector = {
                        'key' : '0'
                        }, 
                    priority_class_name = '0', 
                    runtime_class_name = '0', 
                    scheduler_name = '0', 
                    security_context = None, 
                    tolerations = [
                        None
                        ], 
                    topology_spread_constraints = [
                        None
                        ], 
                    volumes = [
                        None
                        ], ), 
                service_account_name = '0'
            )
        else :
            return V1PipelineTaskRunTemplate(
        )

    def testV1PipelineTaskRunTemplate(self):
        """Test V1PipelineTaskRunTemplate"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
