apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  subdomain: {{ .Values.ingressSubdomain }}
  port:
    targetPort: 8000
  to:
    kind: Service
    name: {{ .Release.Name }}
  tls:
    termination: edge
