# Copyright 2021 The Tekton Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# coding: utf-8

"""
    Tekton

    Tekton Pipeline  # noqa: E501

    The version of the OpenAPI document: v0.17.2
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from tekton_pipeline.configuration import Configuration


class V1Provenance(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'feature_flags': 'GithubComTektoncdPipelinePkgApisConfigFeatureFlags',
        'ref_source': 'V1RefSource'
    }

    attribute_map = {
        'feature_flags': 'featureFlags',
        'ref_source': 'refSource'
    }

    def __init__(self, feature_flags=None, ref_source=None, local_vars_configuration=None):  # noqa: E501
        """V1Provenance - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._feature_flags = None
        self._ref_source = None
        self.discriminator = None

        if feature_flags is not None:
            self.feature_flags = feature_flags
        if ref_source is not None:
            self.ref_source = ref_source

    @property
    def feature_flags(self):
        """Gets the feature_flags of this V1Provenance.  # noqa: E501


        :return: The feature_flags of this V1Provenance.  # noqa: E501
        :rtype: GithubComTektoncdPipelinePkgApisConfigFeatureFlags
        """
        return self._feature_flags

    @feature_flags.setter
    def feature_flags(self, feature_flags):
        """Sets the feature_flags of this V1Provenance.


        :param feature_flags: The feature_flags of this V1Provenance.  # noqa: E501
        :type: GithubComTektoncdPipelinePkgApisConfigFeatureFlags
        """

        self._feature_flags = feature_flags

    @property
    def ref_source(self):
        """Gets the ref_source of this V1Provenance.  # noqa: E501


        :return: The ref_source of this V1Provenance.  # noqa: E501
        :rtype: V1RefSource
        """
        return self._ref_source

    @ref_source.setter
    def ref_source(self, ref_source):
        """Sets the ref_source of this V1Provenance.


        :param ref_source: The ref_source of this V1Provenance.  # noqa: E501
        :type: V1RefSource
        """

        self._ref_source = ref_source

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1Provenance):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V1Provenance):
            return True

        return self.to_dict() != other.to_dict()
